[theme]
primaryColor = "#4F7942"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#E8F5E8"
textColor = "#2F4F2F"

[browser]
gatherUsageStats = false

[server]
runOnSave = false
maxUploadSize = 50

[client]
showErrorDetails = true
