# Copy this to .streamlit/secrets.toml for local development
# For Streamlit Cloud deployment, add these secrets in your app's settings

ANTHROPIC_API_KEY = "your-anthropic-api-key-here"
CLAUDE_MODEL = "claude-3-opus-20240229"
