# Copy this to .streamlit/secrets.toml for local development
# For Streamlit Cloud deployment, add these secrets in your app's settings

ANTHROPIC_API_KEY = "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"
CLAUDE_MODEL = "claude-3-opus-20240229"
